<?php
/**
 * This file describes a Target, which are generated by TargetGenerators
 *
 * @copyright Copyright 2012 Web Courseworks, Ltd.
 * @license   http://www.gnu.org/licenses/gpl-2.0.txt GNU Public License 2.0
 *
 * This file is intended to be included with the ACR
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * http://www.gnu.org/licenses/gpl-2.0.txt
 */

/**
 * A Class to represent a target to be reviewed
 *
 * @author dwipperfurth
 */
abstract class Target {
    
    const VERSION = '1.0';  //The version number of the Target class
   
    /**
     * Setter Constructor
     * 
     * @param string $path  The name of the CodeReviewer
     */
    public abstract function __construct(stdClass $defaultConfig=null);
    
    public abstract function getContents();    
    public abstract function getPath();
    public abstract function getName();
    public abstract function getType();
    
    public function __toString(){
        return $this->getPath();
    }
}